### ISSUE TITLE
Items in baubles slots are lost when dying

### ISSUE THREAD

**Issue by Lothrazar** [M4thG33k/TombManyGraves2#5] opened 2017-04-11 07:31 UTC
Also the items do not fall on the ground, just lost

**Comment by M4thG33k** [comment] 2017-04-11 11:48
1) Which versions of Forge/TMG are being used? (And are you playing a public modpack, and if so which one?)
2) Do the Baubles show up in the death inventory list?
3) Which Baubles, specifically, have been lost?

**Comment by Ravin890** [comment] 2017-04-12 03:46
A few players on the server I am on also has this problem.
1. We are using version 3.0.5 of TMG2 with forge 2279 in the modded mischief modpack (public via curse)
2. There is no bauble section, decided to test and look at death sheet and no baubles noted.
3. It looks like it is any baubles you are wearing get voided. The grave is made but worn baubles don't get returned.

**Comment by M4thG33k** [comment] 2017-04-12 12:43
Hmm. If the items don't show up on the death list, then the grave isn't collecting them either. The version of Baubles hasn't changed, so I'll do some testing and see if I can figure out what's going on.

EDIT: I've updated my development environment to the same version of Forge, but I can't reproduce the issue there. There must be some other mod in the pack causing the issue. Do you know of any other mods which perform logic at time of death in the pack?

**Comment by Ravin890** [comment] 2017-04-12 22:46
Only one i can possibly think of is inventory pets

**Comment by JSmalley1** [comment] 2017-04-13 13:17
I'll have to try to figure it out next week (travelling this weekend). If anyone is able to do tests and narrow down which mod is causing the incompatibility, it will speed up the process (but I don't expect anyone to actually do that...)

**Comment by M4thG33k** [comment] 2017-04-13 13:18
I'll have to try to figure it out next week (travelling this weekend). If anyone is able to do tests and narrow down which mod is causing the incompatibility, it will speed up the process (but I don't expect anyone to actually do that...)

**Comment by Ravin890** [comment] 2017-04-13 17:05
I may actually do a few tests with that today or tomorrow and attempt to narrow it down that way it can be faster to identify and fix problem.
-tested with just baubles, inventory pets, and TMG2 and no issues. So testing with removing mods slowly.
--narrowed down to around 10 mods
---Found it.

So i am running forge 2279 with baubles v1.4.3 , cosmetic armor reworked ,v1a ,  and tomb many graves 2 v3.0.6 and no bauble kept 
 issue occurs.

**Comment by M4thG33k** [comment] 2017-04-18 13:11
So the issue arises when Cosmetic Armor is installed? That's interesting...

**Comment by Ravin890** [comment] 2017-04-18 15:56
yup.

**Comment by M4thG33k** [comment] 2017-04-18 17:31
I'll try to take a look at it tomorrow and see what's going on. I just recently added compatibility with CosArm again and didn't have anything weird happening in my dev world, so who knows what's going on. :-/

**Comment by M4thG33k** [comment] 2017-04-19 13:04
I loaded up an instance with just forge 2279, Baubles 1.4.3, CosArm v1a, and TMG2 3.0.6 and have NOT been able to reproduce this bug.

**Comment by Ravin890** [comment] 2017-04-20 03:02
that is strange.

**Comment by TheLimePixel** [comment] 2017-05-06 17:39
Yeah, players on my server get the same problem.

**Comment by M4thG33k** [comment] 2017-05-07 02:15
I can't really do too much without a narrow list of mods with which I can reproduce the bug. The previously mentioned list of Baubles, CosArm, TMG2, and forge did not produce an environment in which I could reproduce it. If anyone has another list of mods with which they were able to consistently reproduce this bug, I would like to know.

**Comment by TheLimePixel** [comment] 2017-05-07 06:20
It happened on my pack Modern Skyblock

**Comment by M4thG33k** [comment] 2017-05-24 18:57
As previously stated, I need a _small_ list of mods for which this issue arises in order to track down the cause of the problem. A list of 200+ mods is not small.  Also, if the issue only occurs on servers, it may be due to Sponge (if you're using it; Sponge does weird stuff to the mod somehow).

**Comment by TheLimePixel** [comment] 2017-05-24 19:57
Well it turns out that the Baubles don't get deleted, but the grave simply doesn't pick them up.

**Comment by M4thG33k** [comment] 2017-06-09 18:02
Version 3.0.9 should have a fix for this issue.

**Closed as completed by M4thG33k** 2017-06-09 18:02 UTC
